services:
  - type: web
    name: tele-medecine-nest
    env: node
    plan: starter
    buildCommand: npm run build:render
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 7d
    healthCheckPath: /api/docs 