export const enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMINISTRATEUR = 'ADMINISTRATEUR',
  MEDECIN = 'MEDECIN',
  PERSONNEL_ADMINISTRATIF = 'RECEPTIONNISTE',
  RADIOLOGUE = 'RADIOLOGUE',
  TECHNICIEN = 'TECHNICIEN'
}
