export const enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMINISTRATEUR = 'ADMINISTRATEUR',
  MEDECIN = 'MEDECIN',
  RECEPTIONNISTE = 'RECEPTIONNISTE',
  RADIOLOGUE = 'RADIOLOGUE',
  TECHNICIEN = 'TECHNICIEN'
}
